sudo: required
services:
  - docker
before_install:
  - openssl aes-256-cbc -K $encrypted_ac95eddf77d3_key -iv $encrypted_ac95eddf77d3_iv -inservice-account.json.enc -out service-account.json -d
  - curl https://sdk.cloud.google.com | bash > /dev/null;
  - source $HOME/google-cloud-sdk/path.bash.inc
  - gcloud xomponents update kubectl
  - gcloud auth activate-service-account --key-file service-account.json
  - gcloud config set project complete-kubernetes
  - gcloud config set compute/zone us-central1-a
  - gcloud container clusters get-credentials complete-kubernetes