sudo: required
services:
  - docker
env:
  global:
    - SHA=$(git rev-parse HEAD)
    - CLOUDSDK_CORE_DISABLE_PROMPTS=1
before_install:
  - openssl aes-256-cbc -K $encrypted_ac95eddf77d3_key -iv $encrypted_ac95eddf77d3_iv -inservice-account.json.enc -out service-account.json -d
  - curl https://sdk.cloud.google.com | bash > /dev/null;
  - source $HOME/google-cloud-sdk/path.bash.inc
  - gcloud xomponents update kubectl
  - gcloud auth activate-service-account --key-file service-account.json
  - gcloud config set project complete-kubernetes
  - gcloud config set compute/zone us-central1-a
  - gcloud container clusters get-credentials complete-kubernetes
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker build -t mawglih/react-test -f ./client/Dockerfile.dev ./client
script:
  -docker run mawglih/react-test npm test -- --coverage
deploy:
  provider: script
  script: bash ./deploy.sh
  on:
    branch: master
